version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=GerenciamentoVeiculosDb;Username=postgres;Password=yourpassword123;Port=5432
    depends_on:
      - postgres
    volumes:
      - ~/.aspnet/https:/https:ro

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=GerenciamentoVeiculosDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # Alternative: SQL Server (uncomment if you prefer SQL Server)
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourPassword123!
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql

volumes:
  postgres_data:
  # sqlserver_data:
